from llc1_document_api.app import app
from llc1_document_api.blueprints import register_blueprints
from llc1_document_api.exceptions import register_exception_handlers
from llc1_document_api.extensions import register_extensions

register_extensions(app)
register_exception_handlers(app)
register_blueprints(app)
